// client/src/components/RecipeDetails.vue
<template>
  <section class="section">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <router-link to="/" tag="a">
          <font-awesome-icon
            :icon="angleLeft"
            style="margin-right: 5px;"
          ></font-awesome-icon>
          Bakåt
        </router-link>
      </div>
      <div class="container">
        <h1 class="title">
          {{ recipe.title }}
        </h1>
        <hr />
        <div class="details">
          <rating class="rating" :rating="recipe.rating" />
          {{ recipeType }}
          <div class="description">
            {{ recipe.description }}
          </div>
          <div>
            <a :href="recipe.url">{{ recipe.url }}</a>
          </div>
        </div>
      </div>
    </nav>
  </section>
</template>

<script>
import axios from "axios";
import { faAngleLeft } from "@fortawesome/free-solid-svg-icons";
import { RECIPE_TYPES } from "../common/constants";
import Rating from "./Rating";

export default {
  name: "RecipeDetails",
  props: {
    id: String
  },
  components: {
    Rating
  },
  data() {
    return {
      recipe: {}
    };
  },
  computed: {
    angleLeft() {
      return faAngleLeft;
    },
    recipeType() {
      let recipeType = RECIPE_TYPES.find(x => x.type);
      return recipeType ? recipeType.name : "";
    }
  },
  mounted() {
    axios
      .get(`${process.env.VUE_APP_API_URL}/recipes/${this.id}`)
      .then(response => (this.recipe = response.data.data));
  }
};
</script>

<style lang="scss" scoped>
.container {
  margin-top: 1rem;
  h1 {
    text-align: center;
    margin-bottom: 0.5rem;
  }
  .details {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
    .rating {
      font-size: 1.5rem;
    }
    .description {
      margin: 1.5rem 0;
    }
  }

  hr {
    background-color: lightgray;
    margin: 0.9rem 0;
  }
}
</style>

// client-react/src/views/RecipeDetails.tsx
/** @jsx jsx */

import { jsx } from '@emotion/core';
import tw from 'twin.macro';
import React, { useState, useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faExternalLinkAlt,
  faAngleLeft,
  faEdit,
} from '@fortawesome/free-solid-svg-icons';

import { Recipe } from '../types/index';
import Rating from '../components/Rating';
import recipesJson from '../data/recipes.json';

const Header = tw.header`flex justify-between px-4 mt-4`;

const Main = tw.main`flex flex-wrap justify-between sm:w-full md:w-1/2 px-4 mt-4`;
const RecipeTitle = tw.h1`w-full text-center text-2xl font-semibold border-b border-gray-300 mb-4`;
const RecipeType = tw.span``;
const RecipeDescription = tw.div`w-full my-3`;
const RecipeLink = tw.a`text-green-600`;

const RecipeDetails: React.FC = () => {
  const { id } = useParams();
  const [recipe, setRecipe] = useState<Recipe>();

  useEffect(() => {
    setRecipe(recipesJson.find((r) => r._id === id) as Recipe);
  }, [id]);

  if (recipe)
    return (
      <div>
        <Header>
          <Link tw="flex" to={`/`}>
            <FontAwesomeIcon icon={faAngleLeft} tw="text-2xl mr-1" />
            Bakåt
          </Link>
          <Link tw="flex" to={`/`}>
            <FontAwesomeIcon icon={faEdit} />
          </Link>
        </Header>
        <Main>
          <RecipeTitle>{recipe.title}</RecipeTitle>
          <Rating rating={recipe.rating}></Rating>
          <RecipeType>{recipe.type}</RecipeType>
          <RecipeDescription>{recipe.description}</RecipeDescription>
          <RecipeLink href={recipe.url}>
            Gå till recept <FontAwesomeIcon icon={faExternalLinkAlt} />
          </RecipeLink>
        </Main>
      </div>
    );

  return <div></div>;
};

export default RecipeDetails;
