// client-react/src/views/AddRecipe.tsx
/** @jsx jsx */

import { jsx } from '@emotion/core';
import tw, { styled } from 'twin.macro';
import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAngleLeft,
  faStar as faStarSolid,
} from '@fortawesome/free-solid-svg-icons';
import { faStar as faStarRegular } from '@fortawesome/free-regular-svg-icons';
import { MAX_RATING, RECIPE_TYPES } from '../constants';

const Header = tw.header`flex justify-between px-4 mt-4`;

const Main = tw.main`flex flex-wrap justify-between sm:w-full md:w-1/2 px-4 mt-4`;
const Form = tw.form`flex flex-col`;
const Label = tw.label`flex flex-wrap mb-4`;
const TextInput = tw.input`w-full p-1 rounded-sm`;
const Rating = tw.div`w-full text-yellow-600 text-xl`;
const RatingInput = tw.input`absolute h-0 w-0 cursor-pointer`;

const Type = tw.div`w-full text-xl`;
type TypeProps = {
  selected: boolean;
};
const TypeLabel = styled.label<TypeProps>`
  ${tw`opacity-25`}
  ${({ selected }) => selected && tw`opacity-100`}
`;
const TypeInput = tw.input`absolute h-0 w-0 cursor-pointer`;
const DescriptionInput = tw.textarea`w-full resize-none h-32 p-1`;
const Submit = tw.button`bg-red-300 p-1 rounded-md font-bold`;
const ValidationMessage = tw.span`text-sm font-light text-red-600`;

type RecipeForm = {
  title: string;
  url: string;
  rating: number;
  type: string;
  description: string;
};
const AddRecipe: React.FC = () => {
  const { handleSubmit, register, errors, watch } = useForm<RecipeForm>();
  const onSubmit = (values: RecipeForm) => console.log(values);
  const watchRating = watch('rating');
  const watchType = watch('type');
  return (
    <div>
      <Header>
        <Link tw="flex" to={`/`}>
          <FontAwesomeIcon icon={faAngleLeft} tw="text-2xl mr-1" />
          Bakåt
        </Link>
      </Header>
      <Main>
        <Form onSubmit={handleSubmit(onSubmit)}>
          <Label>
            Titel{' '}
            <TextInput
              type="text"
              name="title"
              placeholder="T.ex. Pasta Carbonara"
              ref={register({
                required: 'Obligatoriskt',
              })}
            ></TextInput>
            {errors.title && (
              <ValidationMessage>{errors.title.message}</ValidationMessage>
            )}
          </Label>

          <Label>
            Länk till recept{' '}
            <TextInput
              type="text"
              name="url"
              ref={register({
                required: 'Obligatoriskt',
              })}
            ></TextInput>
            {errors.url && (
              <ValidationMessage>{errors.url.message}</ValidationMessage>
            )}
          </Label>

          <Label>
            Betyg{' '}
            <Rating>
              {[...Array(MAX_RATING)].map((e, i) => (
                <label key={i + 1}>
                  <RatingInput
                    type="radio"
                    name="rating"
                    ref={register({ required: 'Obligatoriskt' })}
                    value={i + 1}
                  />
                  <FontAwesomeIcon
                    icon={i + 1 <= watchRating ? faStarSolid : faStarRegular}
                  ></FontAwesomeIcon>
                </label>
              ))}
            </Rating>
            {errors.rating && (
              <ValidationMessage>{errors.rating.message}</ValidationMessage>
            )}
          </Label>
          <Label>
            Typ
            <Type>
              {RECIPE_TYPES.map((r, i) => (
                <TypeLabel key={i} selected={watchType === r.type}>
                  <TypeInput
                    type="radio"
                    name="type"
                    ref={register({ required: 'Obligatoriskt' })}
                    value={r.type}
                  />{' '}
                  {r.emoji}
                </TypeLabel>
              ))}
            </Type>
            {errors.type && (
              <ValidationMessage>{errors.type.message}</ValidationMessage>
            )}
          </Label>
          <Label>
            Beskrivning eller kommentar
            <DescriptionInput
              name="description"
              ref={register()}
            ></DescriptionInput>
          </Label>
          <Submit type="submit">Spara</Submit>
        </Form>
      </Main>
    </div>
  );
};

export default AddRecipe;

// client/src/components/AddRecipe.vue
<template>
  <section class="section">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <router-link to="/" tag="a">
          <font-awesome-icon
            :icon="angleLeft"
            style="margin-right: 5px;"
          ></font-awesome-icon>
          Bakåt
        </router-link>
      </div>
    </nav>
    <form id="recipeForm" @submit.prevent="submitRecipe">
      <div class="field">
        <label class="label">Titel</label>
        <div class="control">
          <input
            class="input"
            type="text"
            placeholder="T.ex. Pasta Carbonara"
            v-model="recipe.title"
          />
        </div>
      </div>
      <div class="field">
        <label class="label">Länk till recept</label>
        <div class="control">
          <input
            class="input"
            type="text"
            placeholder="http://www.x.y"
            v-model="recipe.url"
          />
        </div>
      </div>
      <div class="field">
        <label class="label">Betyg</label>
        <div class="control">
          <label class="rating" v-for="n in MAX_RATING" :key="n" :value="n">
            <input type="radio" :value="n" v-model="recipe.rating" />
            <font-awesome-icon :icon="getStarIcon(n)" />
          </label>
        </div>
      </div>
      <div class="field">
        <label class="label">Typ</label>
        <div class="control">
          <label
            v-for="(type, index) in RECIPE_TYPES"
            :key="index"
            class="radio"
          >
            <input type="radio" :value="type.type" v-model="recipe.type" />
            {{ type.name }}
          </label>
        </div>
      </div>
      <div class="field">
        <label class="label">Beskrivning eller kommentarer</label>
        <div class="control">
          <textarea 
            class="textarea" 
            placeholder="Gärna en kort beskrivning av receptet!" 
            v-model="recipe.description"/>
        </div>
      </div>
      
      <button class="button is-link" type="submit">Spara</button>
    </form>
  </section>
</template>

<script>
import axios from "axios";
import { faStar as faStarSolid, faAngleLeft } from "@fortawesome/free-solid-svg-icons";
import { faStar as faStarRegular } from "@fortawesome/free-regular-svg-icons";
import { MAX_RATING, RECIPE_TYPES } from "../common/constants";

export default {
  name: "AddRecipe",
  data() {
    return {
      MAX_RATING: MAX_RATING,
      RECIPE_TYPES: RECIPE_TYPES,
      recipe: {
        title: null,
        url: null,
        type: null,
        rating: null,
        description: null
      }
    };
  },
  computed: {
    angleLeft() {
      return faAngleLeft;
    }    
  },
  methods: {
    submitRecipe() {
      axios
        .post(`${process.env.VUE_APP_API_URL}/recipes`, this.recipe)
        .then(() => this.$router.push({ name: "home" }));
    },
    getStarIcon(index) {
      if (this.recipe.rating === null) return faStarRegular;
      else if (index <= this.recipe.rating) return faStarSolid;
      return faStarRegular;
    }
  }
};
</script>

<style lang="scss" scoped>
.rating {
  input {
    position: absolute;
    opacity: 0;
    cursor: pointer;
    height: 0;
    width: 0;
  }
}
</style>
